<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dc="http://purl.org/dc/elements/1.1/" version="1.0">
<xsl:output doctype-public="-//W3C//DTD HTML 4.01 STRICT//EN" encoding="UTF-8" />
<xsl:template match="/PAGE">
<html>
<head>
<meta name="viewport" content="width=device-width" />
<meta name="generator" content="WebMaker" />
<meta name="author" content="Teco a.s." />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache, must-revalidate" />
<meta http-equiv="expires" content="0" />
<link rel="shortcut icon" href="FAVICON.ICO" type="image/x-icon" />
<link href="STYLE.CSS" rel="stylesheet" type="text/css" />
<title>
<xsl:value-of select="/PAGE/@TITLE" />
Home</title>
<script src="HOME.JS?U=1584525588" language="JavaScript" charset="utf-8" />
<style type="text/css">.mono {font-family: Verdana, Arial, FreeSans, sans-serif;}</style>
</head>
<body onload="GetXML('HOME.XML'); FunWatchDog();" style="margin: 0px 0px 0px 0px">
<xsl:if test="1584525588 != ACCESS/@UCID">
<xsl:attribute name="onload">
null;
</xsl:attribute>
<div id="cachewarning" style="text-align: left;"></div>
<script src="REFCLR.JS" language="JavaScript" charset="utf-8"></script>
</xsl:if>
<xsl:if test="1584525588 = ACCESS/@UCID">
<table cellpadding="0" cellspacing="0">
<tr>
<!--menu-->
<!--plan-->
<td id="page" style="border-left: 1px solid black; border-top: 1px solid black;">
<div style="background-color:#969696;position: relative; width: 412px; height: 734px;">
<form action="javascript:PostGlobal();"></form>
<div style="position: absolute; top: 14px; left: 10px; z-index: 1; background-image: url(IMAGES/TECO-LOG.PNG); line-height: 31px; height: 31px; width: 150px;"></div>
<a href="KITCHEN.XML" class="ablock" style="position: absolute; top: 105px; left: 14px; z-index: 2; background-image: url(IMAGES/KITCHEN-.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 108px; left: 51px; z-index: 3; font-size: 12px; color: #FFFFFF;">Kitchen</div>
<a href="DINING.XML" class="ablock" style="position: absolute; top: 105px; left: 144px; z-index: 4; background-image: url(IMAGES/DINING_-.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<a href="LIVING.XML" class="ablock" style="position: absolute; top: 105px; left: 279px; z-index: 5; background-image: url(IMAGES/LIVING_-.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 108px; left: 166px; z-index: 6; font-size: 12px; color: #FFFFFF;">Dining Room</div>
<div style="position: absolute; top: 108px; left: 301px; z-index: 7; font-size: 12px; color: #FFFFFF;">Living Room</div>
<a href="SERVICE.XML" class="ablock" style="position: absolute; top: 232px; left: 14px; z-index: 8; background-image: url(IMAGES/SERVICE_.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 235px; left: 31px; z-index: 9; font-size: 12px; color: #FFFFFF;">Service Room</div>
<a href="ENTRANCE.XML" class="ablock" style="position: absolute; top: 232px; left: 144px; z-index: 10; background-image: url(IMAGES/BATH_-_C.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 235px; left: 148px; z-index: 11; font-size: 12px; color: #FFFFFF;">Interance &amp;  Bath</div>
<a href="MASTER.XML" class="ablock" style="position: absolute; top: 232px; left: 279px; z-index: 12; background-image: url(IMAGES/BED_-_CA.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 235px; left: 297px; z-index: 13; font-size: 12px; color: #FFFFFF;">Master Room</div>
<a href="MAJLES.XML" class="ablock" style="position: absolute; top: 358px; left: 14px; z-index: 14; background-image: url(IMAGES/MAJLES_-.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 361px; left: 54px; z-index: 15; font-size: 12px; color: #FFFFFF;">Majles</div>
<a href="ROOM1.XML" class="ablock" style="position: absolute; top: 358px; left: 146px; z-index: 16; background-image: url(IMAGES/BED_-_CA.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 361px; left: 184px; z-index: 17; font-size: 12px; color: #FFFFFF;">Room1</div>
<a href="ROOM2.XML" class="ablock" style="position: absolute; top: 358px; left: 279px; z-index: 18; background-image: url(IMAGES/BED_-_CA.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 361px; left: 317px; z-index: 19; font-size: 12px; color: #FFFFFF;">Room2</div>
<a href="ROOM3.XML" class="ablock" style="position: absolute; top: 485px; left: 14px; z-index: 20; background-image: url(IMAGES/BED_-_CA.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 488px; left: 52px; z-index: 21; font-size: 12px; color: #FFFFFF;">Room3</div>
<a href="ROOM4.XML" class="ablock" style="position: absolute; top: 485px; left: 146px; z-index: 22; background-image: url(IMAGES/BED_-_CA.PNG); line-height: 84px; height: 84px; width: 120px;"></a>
<div style="position: absolute; top: 488px; left: 184px; z-index: 23; font-size: 12px; color: #FFFFFF;">Room4</div>
</div>
</td>
</tr>
<!--bottom-->
<tr style="height: 10px;">
<td id="bottom" colspan="2" style="text-align: center">© 2007 - 2020 Teco a.s.</td>
</tr>
</table>
</xsl:if>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
